all: part1

part1:
	g++ mp.cpp -o mp -lm -fopenmp
	./mp

# all:
# 	sh proj6part1.sh
# 	sh proj6part2.sh

# part1:
# 	sh proj6part1.sh
#
# part2:
# 	sh proj6part2.sh

clean:
	rm -r proj6part1 proj6part2 *.csv mp
